name: CI
on:
  pull_request:
    branches:
      - 'main'
env:
  IMAGE_TAG: latest
jobs:
  rest:
    name: REST API
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/tomkerkhove/bacon-api
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./src/Bacon.API --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  grpc:
    name: gRPC Service
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/tomkerkhove/grpc-bacon
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./src/Bacon.gRPC.Service --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
