name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
env:
  IMAGE_TAG: latest
jobs:
  rest:
    name: REST API
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/tomkerkhove/bacon-api
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./src/ --file ./src/Bacon.API/Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  grpc:
    name: gRPC Service
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/tomkerkhove/grpc-bacon
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./src --file ./src/Bacon.gRPC.Service/Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
