name: Push Image to GitHub Container Registry
on:
  push:
    paths:
    - '.github/workflows/push-image-to-ghcr.yml'
    - 'src/**'
    branches:
    - master
env:
  IMAGE_TAG: latest
jobs:
  push:
    name: Push GHCR
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/tomkerkhove/bacon-api
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: ghcr.io
        username: tomkerkhove
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build src\Bacon.API --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
    - name: Push the Docker image
      run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}